#![cfg_attr(not(feature = "std"), no_std)]
#![no_main]

use optee_utee::prelude::*;
use optee_utee::{ErrorKind, Result};

// Command IDs — these must match the values used by the host application.
// The optee-utee-build crate does not auto-generate command constants.
pub const TA_CMD_INC_VALUE: u32 = 0;
pub const TA_CMD_DEC_VALUE: u32 = 1;

#[ta_create]
fn ta_create() -> Result<()> {
    trace_println!("Trusted Application entry point created");
    Ok(())
}

#[ta_destroy]
fn ta_destroy() {
    trace_println!("Trusted Application destroyed");
}

#[ta_open_session]
fn ta_open_session(_params: &mut ParametersNone) -> Result<()> {
    trace_println!("Session opened");
    Ok(())
}

#[ta_close_session]
fn ta_close_session() {
    trace_println!("Session closed");
}

#[ta_invoke_command]
fn ta_invoke_command(
    cmd_id: u32,
    params: &mut (
        ParameterValueInout,
        ParameterNone,
        ParameterNone,
        ParameterNone,
    ),
) -> Result<()> {
    let values = &mut params.0;
    trace_println!("Command invoked: {}", cmd_id);
    match cmd_id {
        TA_CMD_INC_VALUE => {
            trace_println!("Got value: {} from normal world", values.get_a());
            values.set_a(values.get_a() + 1);
            trace_println!("Echoed (incremented) value to: {}", values.get_a());
            Ok(())
        }
        TA_CMD_DEC_VALUE => {
            trace_println!("Got value: {} from normal world", values.get_a());
            values.set_a(values.get_a() - 1);
            trace_println!("Decreased value to: {}", values.get_a());
            Ok(())
        }
        _ => Err(ErrorKind::BadParameters.into()),
    }
}

// ---- TA header (generated by optee-utee-build) must be included at the end ----
include!(concat!(env!("OUT_DIR"), "/user_ta_header.rs"));
