// SPDX-License-Identifier: MIT

#![cfg_attr(not(feature = "std"), no_std)]
#![no_main]

use optee_utee::{
    ta_close_session, ta_create, ta_destroy, ta_invoke_command, ta_open_session, trace_println,
    Error, ErrorKind, ParamType, Parameters, Result,
};
use ta_common::Command;

#[ta_create]
fn ta_create() -> Result<()> {
    trace_println!("Trusted Application entry point created");
    Ok(())
}

#[ta_destroy]
fn ta_destroy() {
    trace_println!("Trusted Application destroyed");
}

#[ta_open_session]
fn ta_open_session(_: &mut Parameters) -> Result<()> {
    trace_println!("Session opened");
    Ok(())
}

#[ta_close_session]
fn ta_close_session() {
    trace_println!("Session closed");
}

/// Dispatches TA commands received from the normal world.
///
/// Expects a single `ValueInout` parameter (arg 0) carrying a `u32` value.
/// - `Command::IncValue`: increments the value by 1 and echoes it back.
/// - `Command::DecValue`: decrements the value by 1 and echoes it back.
/// Returns `BadParameters` if the argument type is not a value parameter or
/// if arithmetic would overflow/underflow.
#[ta_invoke_command]
fn ta_invoke_command(cmd_id: u32, params: &mut Parameters) -> Result<()> {
    trace_println!("Command invoked: {}", cmd_id);

    // Validate parameter direction — TA expects ValueInout only.
    if !matches!(params.0.param_type, ParamType::ValueInout) {
        return Err(ErrorKind::BadParameters.into());
    }
    // SAFETY: The OP-TEE entry-point wrapper constructs this parameter from its valid
    // TEE_Param array; the type check above confirms that value was set in this slot.
    let mut value = unsafe { params.0.as_value() }?;

    let cmd = Command::try_from(cmd_id).map_err(|_| Error::from(ErrorKind::BadParameters))?;
    match cmd {
        Command::IncValue => value
            .a()
            .checked_add(1)
            .map(|v| {
                value.set_a(v);
                trace_println!("Incremented value: {}", value.a());
            })
            .ok_or(ErrorKind::BadParameters.into()),
        Command::DecValue => value
            .a()
            .checked_sub(1)
            .map(|v| {
                value.set_a(v);
                trace_println!("Decremented value: {}", value.a());
            })
            .ok_or(ErrorKind::BadParameters.into()),
    }
}

// ---- TA header (generated by optee-utee-build) must be included at the end ----
include!(concat!(env!("OUT_DIR"), "/user_ta_header.rs"));
