[package]
name = "hello-world-host"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
optee-teec = { workspace = true }
optee-teec-build = { workspace = true }
optee-teec-sys = { workspace = true }
ta-common = { path = "../ta-common" }
